#cloud-config
variant: fcos
version: 1.3.0
systemd:
  units:
    - name: amazon-ecs-agent.service
      enabled: true
      contents: |
        [Unit]
        Description=AWS ECS Agent
        Documentation=https://docs.aws.amazon.com/AmazonECS/latest/developerguide/
        Requires=docker.socket
        After=docker.socket

        [Service]
        Environment=ECS_CLUSTER=${ecs_cluster_name}
        Restart=on-failure
        RestartSec=30
        RestartPreventExitStatus=5
        SyslogIdentifier=ecs-agent
        ExecStartPre=-/bin/mkdir -p /var/log/ecs /var/ecs-data /etc/ecs
        ExecStartPre=-/bin/podman kill ecs-agent
        ExecStartPre=-/bin/podman rm ecs-agent
        ExecStartPre=/bin/podman pull docker.io/amazon/amazon-ecs-agent:latest
        ExecStart=/bin/podman run --name ecs-agent --privileged \
                                      --volume=/var/run/docker.sock:/var/run/docker.sock \
                                      --volume=/var/log/ecs:/log \
                                      --volume=/var/ecs-data:/data \
                                      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
                                      --publish=127.0.0.1:51678:51678 \
                                      --env=ECS_LOGFILE=/log/ecs-agent.log \
                                      --env=ECS_LOGLEVEL=info \
                                      --env=ECS_DATADIR=/data \
                                      --env=ECS_CLUSTER=$${ECS_CLUSTER} \
                                      docker.io/amazon/amazon-ecs-agent:latest

        [Install]
        WantedBy=multi-user.target